export const africanProvinces: Record<string, string[]> = {
  "Algeria": [
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Algiers",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arréridj",
    "Boumerdès",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Aïn Defla",
    "Naâma",
    "Aïn Témouchent",
    "Ghardaïa",
    "Relizane",
    "Timimoun",
    "Bordj Badji Mokhtar",
    "Ouled Djellal",
    "Béni Abbès",
    "In Salah",
    "In Guezzam",
    "Touggourt",
    "Djanet",
    "El M'Ghair",
    "El Meniaa"
  ],
  "Angola": [
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Norte",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huíla",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire"
  ],
  "Benin": [
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Couffo",
    "Donga",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou"
  ],
  "Botswana": [
    "Central",
    "Chobe",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "North-East",
    "North-West",
    "South-East",
    "Southern"
  ],
  "Burkina Faso": [
    "Boucle du Mouhoun",
    "Cascades",
    "Centre",
    "Centre-Est",
    "Centre-Nord",
    "Centre-Ouest",
    "Centre-Sud",
    "Est",
    "Hauts-Bassins",
    "Nord",
    "Plateau-Central",
    "Sahel",
    "Sud-Ouest"
  ],
  "Burundi": [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rumonge",
    "Rutana",
    "Ruyigi"
  ],
  "Cabo Verde": [
    "Boa Vista",
    "Brava",
    "Maio",
    "Mosteiros",
    "Paul",
    "Porto Novo",
    "Praia",
    "Ribeira Brava",
    "Ribeira Grande",
    "Ribeira Grande de Santiago",
    "Sal",
    "Santa Catarina",
    "Santa Catarina do Fogo",
    "Santa Cruz",
    "São Domingos",
    "São Filipe",
    "São Lourenço dos Órgãos",
    "São Miguel",
    "São Nicolau",
    "São Salvador do Mundo",
    "São Vicente",
    "Tarrafal",
    "Tarrafal de São Nicolau"
  ],
  "Cameroon": [
    "Adamaoua",
    "Centre",
    "East",
    "Far North",
    "Littoral",
    "North",
    "Northwest",
    "South",
    "Southwest",
    "West"
  ],
  "Central African Republic": [
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Haute-Kotto",
    "Haut-Mbomou",
    "Kémo",
    "Lobaye",
    "Mambéré-Kadéï",
    "Mbomou",
    "Nana-Grébizi",
    "Nana-Mambéré",
    "Ombella-M'Poko",
    "Ouaka",
    "Ouham",
    "Ouham-Pendé",
    "Sangha-Mbaéré",
    "Vakaga"
  ],
  "Chad": [
    "Batha",
    "Borkou",
    "Chari-Baguirmi",
    "Ennedi-Est",
    "Ennedi-Ouest",
    "Guéra",
    "Hadjer-Lamis",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kebbi Est",
    "Mayo-Kebbi Ouest",
    "Moyen-Chari",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "Wadi Fira",
    "N'Djamena"
  ],
  "Comoros": [
    "Grande Comore (Ngazidja)",
    "Anjouan (Ndzuwani)",
    "Mohéli (Mwali)"
  ],
  "Democratic Republic of the Congo": [
    "Bas-Uele",
    "Bord Tanganika",
    "Équateur",
    "Haut-Katanga",
    "Haut-Lomami",
    "Haut-Uele",
    "Ituri",
    "Kasaï",
    "Kasaï-Central",
    "Kasaï-Oriental",
    "Kinshasa",
    "Kongo Central",
    "Kwango",
    "Kwilu",
    "Lomami",
    "Lualaba",
    "Mai-Ndombe",
    "Maniema",
    "Mongala",
    "Nord-Kivu",
    "Nord-Ubangi",
    "Sankuru",
    "Sud-Kivu",
    "Sud-Ubangi",
    "Tanganyika",
    "Tshopo",
    "Tshuapa"
  ],
  "Republic of the Congo": [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Lékoumou",
    "Likouala",
    "Niari",
    "Plateaux",
    "Pointe-Noire",
    "Pool",
    "Sangha"
  ],
  "Côte d'Ivoire": [
    "Abidjan",
    "Bas-Sassandra",
    "Comoé",
    "Denguélé",
    "Gôh-Djiboua",
    "Lacs",
    "Lagunes",
    "Montagnes",
    "Sassandra-Marahoué",
    "Savanes",
    "Vallée du Bandama",
    "Woroba",
    "Yamoussoukro",
    "Zanzan"
  ],
  "Djibouti": [
    "Ali Sabieh",
    "Arta",
    "Dikhil",
    "Djibouti",
    "Obock",
    "Tadjourah"
  ],
  "Egypt": [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez"
  ],
  "Equatorial Guinea": [
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Djibloho",
    "Kié-Ntem",
    "Litoral",
    "Wele-Nzas"
  ],
  "Eritrea": [
    "Anseba",
    "Central (Maekel)",
    "Gash-Barka",
    "Northern Red Sea",
    "Southern (Debub)",
    "Southern Red Sea"
  ],
  "Eswatini": [
    "Hhohho",
    "Lubombo",
    "Manzini",
    "Shiselweni"
  ],
  "Ethiopia": [
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Benishangul-Gumuz",
    "Dire Dawa",
    "Gambela",
    "Harari",
    "Oromia",
    "Sidama",
    "Somali",
    "South West Ethiopia Peoples' Region",
    "Southern Nations, Nationalities, and Peoples' Region",
    "Tigray"
  ],
  "Gabon": [
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem"
  ],
  "The Gambia": [
    "Banjul",
    "Central River",
    "Lower River",
    "North Bank",
    "Upper River",
    "West Coast"
  ],
  "Ghana": [
    "Ahafo",
    "Ashanti",
    "Bono",
    "Bono East",
    "Central",
    "Eastern",
    "Greater Accra",
    "North East",
    "Northern",
    "Oti",
    "Savannah",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
    "Western North"
  ],
  "Guinea": [
    "Boké",
    "Conakry",
    "Faranah",
    "Kankan",
    "Kindia",
    "Labé",
    "Mamou",
    "Nzérékoré"
  ],
  "Guinea-Bissau": [
    "Bafatá",
    "Biombo",
    "Bissau",
    "Bolama",
    "Cacheu",
    "Gabu",
    "Oio",
    "Quinara",
    "Tombali"
  ],
  "Kenya": [
    "Baringo",
    "Bomet",
    "Bungoma",
    "Busia",
    "Elgeyo-Marakwet",
    "Embu",
    "Garissa",
    "Homa Bay",
    "Isiolo",
    "Kajiado",
    "Kakamega",
    "Kericho",
    "Kiambu",
    "Kilifi",
    "Kirinyaga",
    "Kisii",
    "Kisumu",
    "Kitui",
    "Kwale",
    "Laikipia",
    "Lamu",
    "Machakos",
    "Makueni",
    "Mandera",
    "Marsabit",
    "Meru",
    "Migori",
    "Mombasa",
    "Murang'a",
    "Nairobi",
    "Nakuru",
    "Nandi",
    "Narok",
    "Nyamira",
    "Nyandarua",
    "Nyeri",
    "Samburu",
    "Siaya",
    "Taita-Taveta",
    "Tana River",
    "Tharaka-Nithi",
    "Trans Nzoia",
    "Turkana",
    "Uasin Gishu",
    "Vihiga",
    "Wajir",
    "West Pokot"
  ],
  "Lesotho": [
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka"
  ],
  "Liberia": [
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "Rivercess",
    "River Gee",
    "Sinoe"
  ],
  "Libya": [
    "Al Butnan",
    "Al Jabal al Akhdar",
    "Al Jabal al Gharbi",
    "Al Jafara",
    "Al Jufrah",
    "Al Kufrah",
    "Al Marqab",
    "Al Wahat",
    "An Nuqat al Khams",
    "Az Zawiyah",
    "Benghazi",
    "Darnah",
    "Ghat",
    "Misratah",
    "Murzuq",
    "Nalut",
    "Sebha",
    "Sirte",
    "Tripoli",
    "Wadi al Hayaa",
    "Wadi ash Shati"
  ],
  "Madagascar": [
    "Diana",
    "Sava",
    "Itasy",
    "Analamanga",
    "Vakinankaratra",
    "Bongolava",
    "Sofia",
    "Boeny",
    "Betsiboka",
    "Melaky",
    "Alaotra-Mangoro",
    "Atsinanana",
    "Analanjirofo",
    "Ambatosoa",
    "Amoron'i Mania",
    "Haute Matsiatra",
    "Vatovavy",
    "Fitovinany",
    "Atsimo-Atsinanana",
    "Ihorombe",
    "Menabe",
    "Atsimo-Andrefana",
    "Androy",
    "Anosy"
  ],
  "Malawi": [
    "Balaka",
    "Blantyre",
    "Chikwawa",
    "Chiradzulu",
    "Chitipa",
    "Dedza",
    "Dowa",
    "Karonga",
    "Kasungu",
    "Likoma",
    "Lilongwe",
    "Machinga",
    "Mangochi",
    "Mchinji",
    "Mulanje",
    "Mwanza",
    "Mzimba",
    "Neno",
    "Nkhata Bay",
    "Nkhotakota",
    "Nsanje",
    "Ntcheu",
    "Ntchisi",
    "Phalombe",
    "Rumphi",
    "Salima",
    "Thyolo",
    "Zomba"
  ],
  "Mali": [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Ménaka",
    "Mopti",
    "Ségou",
    "Sikasso",
    "Taoudénit",
    "Tombouctou"
  ],
  "Mauritania": [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouadhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott-Nord",
    "Nouakchott-Ouest",
    "Nouakchott-Sud",
    "Tagant",
    "Tiris Zemmour",
    "Trarza"
  ],
  "Mauritius": [
    "Agaléga",
    "Cargados Carajos",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Rivière du Rempart",
    "Rivière Noire",
    "Rodrigues",
    "Savanne"
  ],
  "Morocco": [
    "Tanger-Tetouan-Al Hoceima",
    "Oriental",
    "Fès-Meknès",
    "Rabat-Salé-Kénitra",
    "Béni Mellal-Khénifra",
    "Casablanca-Settat",
    "Marrakech-Safi",
    "Drâa-Tafilalet",
    "Souss-Massa",
    "Guelmim-Oued Noun",
    "Laâyoune-Sakia El Hamra",
    "Dakhla-Oued Ed-Dahab"
  ],
  "Mozambique": [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo (City)",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambézia"
  ],
  "Namibia": [
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango East",
    "Kavango West",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa",
    "Zambezi"
  ],
  "Niger": [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillabéri",
    "Zinder"
  ],
  "Nigeria": [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "FCT",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  "Rwanda": [
    "Kigali City",
    "Eastern Province",
    "Northern Province",
    "Western Province",
    "Southern Province"
  ],
  "Sao Tome and Principe": [
    "Água Grande",
    "Cantagalo",
    "Caué",
    "Lembá",
    "Lobata",
    "Mé-Zóchi",
    "Príncipe"
  ],
  "Senegal": [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Ziguinchor"
  ],
  "Seychelles": [
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Anse Royale",
    "Au Cap",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "Glacis",
    "Grand'Anse (Mahé)",
    "Grand'Anse (Praslin)",
    "Inner Islands",
    "English River",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Roche Caiman",
    "Saint Louis",
    "Takamaka",
    "Les Mamelles"
  ],
  "Sierra Leone": [
    "Eastern",
    "Northern",
    "North Western",
    "Southern",
    "Western Area"
  ],
  "Somalia": [
    "Awdal",
    "Bakool",
    "Banaadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiiraan",
    "Jubbada Dhexe",
    "Jubbada Hoose",
    "Mudug",
    "Nugaal",
    "Sanaag",
    "Shabeellaha Dhexe",
    "Shabeellaha Hoose",
    "Sool",
    "Togdheer"
  ],
  "South Africa": [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape"
  ],
  "South Sudan": [
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei",
    "Lakes",
    "Northern Bahr el Ghazal",
    "Unity",
    "Upper Nile",
    "Warrap",
    "Western Bahr el Ghazal",
    "Western Equatoria",
    "Pibor",
    "Rueng",
    "Abyei"
  ],
  "Sudan": [
    "Al Jazirah",
    "Al Qadarif",
    "Blue Nile",
    "Central Darfur",
    "East Darfur",
    "Kassala",
    "Khartoum",
    "North Darfur",
    "North Kordofan",
    "Northern",
    "Red Sea",
    "River Nile",
    "Sennar",
    "South Darfur",
    "South Kordofan",
    "West Darfur",
    "West Kordofan",
    "White Nile"
  ],
  "Tanzania": [
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kagera",
    "Katavi",
    "Kigoma",
    "Kilimanjaro",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Njombe",
    "Pemba North",
    "Pemba South",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Simiyu",
    "Singida",
    "Songwe",
    "Tabora",
    "Tanga",
    "Zanzibar North",
    "Zanzibar South and Central",
    "Zanzibar West"
  ],
  "Togo": [
    "Centrale",
    "Kara",
    "Maritime",
    "Plateaux",
    "Savanes"
  ],
  "Tunisia": [
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan"
  ],
  "Uganda": [
    "Central",
    "Eastern",
    "Northern",
    "Western"
  ],
  "Zambia": [
    "Central",
    "Copperbelt",
    "Eastern",
    "Luapula",
    "Lusaka",
    "Muchinga",
    "Northern",
    "North-Western",
    "Southern",
    "Western"
  ],
  "Zimbabwe": [
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands"
  ],
  "Western Sahara": [
    "Boujdour",
    "Es Semara",
    "Laayoune",
    "Oued Ed-Dahab"
  ]
};
